### PR TITLE
Plot edits

### PR DESCRIPTION
**Pull request by jradrion**
I added a few lines that dump the raw results from each method to a .txt file, which can then be plotted in R to generate the final figures.

### CODE REVIEW

**Comment by andrewkern** [comment]
where is this going to store these intermediates?

**Comment by jradrion** [comment]
It stores them in the /Results directory, where the original auto-generated pdf is written.

**Comment by andrewkern** [comment]
cool. can you squash these down to one commit?

**Comment by jradrion** [comment]
done. thanks!

**Pull request merged**
