### PR TITLE
Revert "added smc++ analysis section, associated utils, and snakemake rules"

### PR DESCRIPTION
**Pull request by andrewkern**
Reverts popgensims/analysis#9

### CODE REVIEW

**Comment by andrewkern** [comment]
@jeromekelleher can you revert this? i must have pushed something bad on that PR

**Comment by jeromekelleher** [comment]
Do you want me to do something here @andrewkern, or has it sorted itself out?

**Comment by andrewkern** [comment]
all set- found my screw up and corrected it. sorry to bother

**Comment by jeromekelleher** [comment]
> all set- found my screw up and corrected it. sorry to bother

No worries.

**Pull request closed without merging**
