### PR TITLE
added LD filtering changes to improve stairwayplot

### PR DESCRIPTION
**Pull request by jradrion**
Made a number of changes in an attempt to improve the stairwayplot analysis. Modified the config.json by removing `generation_time` and adding `ld_thresh`. `num_sampled_genomes_msmc` was also changed to take a comma-separated string of sample sizes, as to be more consistent with how we take a comma-separated string of chromosomes to simulate. The Snakefile now loads generation time as an attribute of the model. The rule to simulate now runs an optional LD pruning step, whereby all pairs of SNPs with r^2 > some threshold value are excluded from the stairwayplot analysis. Additionally, simulate prints a figure of the SFS for all SNPs from each simulation, along with the SFS for only those SNPs retained after LD filtering. I also added two rules that can be substituted for `rule all` (via commenting) to make future modifications to the stairwayplot analysis easier to implement. One rule just runs the simulations, and one runs only stairwayplot and generates a figure for stairwayplot only. Feel free to remove these rules if you don't feel that they are necessary or "snakic?" enough.

### CODE REVIEW

**Comment by jradrion** [comment]
all_estimated_Ne
Here are some results from a test run using the all chromosomes of the human genome.

**Comment by petrelharp** [comment]
well, those look better. is it because of LD pruning?

**Comment by jgallowa07** [comment]
Hi! These changes sounds fine to me! maybe run Arabidopsis? Human pop1 has always looked pretty good, no?

**Comment by andrewkern** [comment]
LD pruning is definitely helping things for the Stairwayplot. I agree we should run this on Arabidopsis and take a look.

**Comment by jradrion** [comment]
all_estimated_Ne

Here are eight reps from the Arabidopsis model (all chromosomes). Still looking quite poor.

**Pull request merged**
