### PR TITLE
Mask analysis

### PR DESCRIPTION
**Pull request by andrewkern**
opening a PR here with refactored analysis code that will mask on the basis of a bed file that one defines in the `config.json` file. for this i've created a directory at `analysis/n_t/masks` which contains bed formatted masks as well as a script written by @dschride to create them on the basis of the genetic map. 

right now the exact mask we should use is debatable but I want to get this PR going as it allows for the behavior we wish to achieve.

### CODE REVIEW

**Comment by andrewkern** [comment]
> This is working on my end. My only suggestions would be to remove the older ld-based filtering functions to avoid any confusion down the road. Or were you intending to keep both? 

sounds good, i'll ditch the ld-filter mask from the workflow

>To my eyes, the SFS from the masking done here looks much better than it did using the ld-filtering. Also, adding an automated plotting function to compare the masked and unmasked SFS would be nice, which I believe you have already implemented.

yes i have to clean this up a bit still and segregate all the plotting to a single file.

**Comment by andrewkern** [comment]
Okay @jradrion this is all squashed, cleaned, and ready for a merge I believe. Let's try to merge this before we merge the `SMCSMC` PR

**Comment by jradrion** [comment]
OK @andrewkern, just tested this and everything is working on my end!

**Comment by andrewkern** [comment]
okay merging

**Comment by jradrion** [comment]
Good deal! We can probably close the corresponding issue as well.

**Pull request merged**
