### PR TITLE
Add framework for fitting dadi models to simulated data.

### PR DESCRIPTION
**Pull request by RyanGutenkunst**
Rough draft of framework for running dadi on the stdpopsim models. Still work to be done, and needs to be cleaned up, but it's working code at least.

### CODE REVIEW

**Comment by andrewkern** [comment]
Very cool. Will have a look through in the morning. Let's set this up with some reviewers

**Comment by andrewkern** [comment]
also I think we should probably rename the directory to be for a specific task, like `two_population_analysis` or similar. In addition we should probably squash the commits down to a single one before we merge

**Comment by jeromekelleher** [comment]
Just in case you haven't seen it, the docs for rebasing are [here](https://stdpopsim.readthedocs.io/en/latest/development.html#rebasing)

**Comment by andrewkern** [comment]
@tjstruck @RyanGutenkunst-- hoping to merge this code. can you guys make the few changes we requested above and rebase? thanks!

**Comment by RyanGutenkunst** [comment]
My apologies for the delay. It was my fault for filtering my GitHub emails too aggressively. We made the suggested changes and rebased.

Also, we'll dadi on PyPI soonish. (Waiting on adding a significant chunk of code for DFE analysis.)

**Comment by jeromekelleher** [comment]
LGTM; are you happy to merge @andrewkern?

**Comment by andrewkern** [comment]
yup looks great. Thanks @RyanGutenkunst!

**Pull request merged**
