### PR TITLE
Adding smcpp to fsc dadi pipeline

### PR DESCRIPTION
**Pull request by dortegadelv**
Adding smc++ to the pipeline started by Chris Kyriazis. After running this pipeline we will get results from fastsimcoal2, dadi and smc++. This version of the pipeline only works when the chromosome 22 is the only chromosome specified in the json file. I will work on fixing this later. However, I got the first results from running this whole pipeline using the Gutenkunst model:

estimates_N_tdiv_dadi_fsc pngsmcpp

In the case of SMC++ I only report the values of N1 and N2 using the harmonic mean. I also report the divergence time for SMC++. Those values are underestimated compared to the true values. SMC++ assumes a model where there is no post-divergence gene flow, so the violation to this assumption is probably the culprit behind the underestimations. The review "Inference of population history using coalescent HMMs: review and outlook" from Spence et al (2018) reports: "Users should also be careful about model choice. As an example, SMC++ infers population splits in the absence of gene flow. If there has been pervasive migration between the populations of interest, then the model inferred by SMC++ will not be reflective of reality." The amount of gene flow postdivergence in the Gutenkunst model is sufficient to be a violation of this assumption. It would be good to have a model in stdpopsim where there is no post-divergence gene flow to confirm that SMC++ is working well on that setting.

I also have a plot with the output of 10 SMC++ runs, shown here below. @petrelharp you mentioned that you had a way to combine the results from the SMC++ runs. Let me know what is your suggestion to present these results.

smcpp_estimated_Ne

### CODE REVIEW

**Comment by petrelharp** [comment]
This looks promising, @dortegadelv! Thanks. I don't recall the method you're talking about, maybe it was someone else (@andrewkern maybe?)?

About the plots: the first one would be easier to see if the different methods were offset and not overlapping, or maybe as boxplots. And, what's the vertical blue lines in the second one?

**Comment by dortegadelv** [comment]
Thanks for your comments @petrelharp ! That makes sense, I will play a little bit with the boxplots.

The vertical blue lines are the split times in the second plot are the split times.

I will work on making this pipeline work with more chromosomes, and I will do tests with some alternative demographic models.

**Comment by dortegadelv** [comment]
The pipeline now gets demographic parameter estimates from fastsimcoal, dadi and smc++ using any arbitrary number of chromosomes. Previously it only worked when a single chromosome was specified. I just tested the pipeline by doing simulations under the Gutenkunst model using chromosomes 21 and 22. Some results are shown below:

[EstimatesParameters.pdf](https://github.com/popgensims/analysis/files/3586900/EstimatesParameters.pdf)

The pipeline should work when using the Drosophila demographic model, @ckyriazis . If someone  finds problems when testing the pipeline, please let me know.

**Comment by ckyriazis** [comment]
Awesome, thanks Diego! I will try to run this with Drosophila this week.

**Comment by andrewkern** [comment]
okay we are going to need some reviewers on this. Any volunteers? tagging people in hopes they have time @ckyriazis @jradrion @cjbattey @jgallowa07

**Comment by ckyriazis** [comment]
I'll have a look at it @andrewkern.

**Comment by ckyriazis** [comment]
Hey @dortegadelv, I'm getting this error during the run_scmpp step:
`smc++ estimate: error: argument mu: invalid float value: 'treespop1.smc.gz'`

Any idea what might be causing this?

**Comment by dortegadelv** [comment]
Let me check! Can i get a look at your json file?

**Comment by ckyriazis** [comment]
Yes - here it is: 

`{
    "seed" : 12345,
    "num_sampled_genomes_per_replicate" : 50,
    "replicates" : 10,
    "species" : "drosophila_melanogaster",
    "model" : "LiStephanTwoPopulation",
    "genetic_map" : "Comeron2012_dm6",
    "chrm_list" : "chr2R",
    "generation_time" : "0.1"
}
`

**Comment by dortegadelv** [comment]
Quick question, what is the value of the variable "mutation_rate" in the "LiStephanTwoPopulation" model? I think smc++ is complaining about the value of that variable not being a float value. If that is not the problem, I will think a little bit more about what is going on.

**Comment by andrewkern** [comment]
the `mutation_rate` parameter isn't a property of most demographic model in `stdpopsim`, so it gets set at the time of simulation on the `analysis` side of things. 

for instance in the single population case we set the mutation using the `default_mutation_rate` variable associated with the drosophila genome here https://github.com/popgensims/analysis/blob/607772593ef8042a18d72dea2098e4d55f87dcc0/n_t/simulations.py#L16

**Comment by dortegadelv** [comment]
I see! Yes, I am using the following line to assign the value to the mutation_rate parameter in the Snakemake file:

mutation_rate = species.genome.mean_mutation_rate

I wonder if "species.genome.mean_mutation_rate" is undefined in the "LiStephanTwoPopulation" model. Maybe switching the past line to the following one should do the trick if the definition of the mutation_rate parameter is the problem:

mutation_rate=chrom.default_mutation_rate

**Comment by andrewkern** [comment]
no, what you are doing should work. for instance here are a few lines from the interpreter
```
>>> import stdpopsim
>>> stdpopsim.drosophila_melanogaster.genome.mean_mutation_rate
8.400000000000002e-09
>>> stdpopsim.homo_sapiens.genome.mean_mutation_rate
1e-08
>>> stdpopsim.arabidopsis_thaliana.genome.mean_mutation_rate
7e-09
```
i'll take a look through your code

**Comment by andrewkern** [comment]
i took a quick look and your `Snakefile` looks fine to me in how you are handling `mutation_rate`

**Comment by ckyriazis** [comment]
So following up on this - I thought maybe the error had something to do with subprocess trying to feed 'treespop1.smc.gz' as the mutation rate to smc++. I havent really used either subprocess or smc++ though, so I'm not in the best position to debug.

**Comment by dortegadelv** [comment]
I'll take a look at this. I am going to run the program using your json file to see what is going on.

**Comment by dortegadelv** [comment]
I am trying to run the "LiStephanTwoPopulation" model using @ckyriazis json file and I am getting these errors:

TypeError in line 48 of /Users/vicentediegoortegadelvecchyo/Dropbox/Documents/LIIGH/Proyectos/PopSim/AlternativeBranch/analysis-2fcf02fccca7ff2f21073fedbc66d65b73c873d5copy/two_population_analysis/Snakefile:
__init__() got an unexpected keyword argument 'metadata'
  File "/Users/vicentediegoortegadelvecchyo/Dropbox/Documents/LIIGH/Proyectos/PopSim/AlternativeBranch/analysis-2fcf02fccca7ff2f21073fedbc66d65b73c873d5copy/two_population_analysis/Snakefile", line 48, in <module>
  File "/Users/vicentediegoortegadelvecchyo/miniconda3/envs/popsim_env_test/lib/python3.6/site-packages/stdpopsim-0.1.dev149+gfe658a2-py3.6.egg/stdpopsim/drosophila_melanogaster.py", line 138, in __init__
ERROR:snakemake.logging:TypeError in line 48 of /Users/vicentediegoortegadelvecchyo/Dropbox/Documents/LIIGH/Proyectos/PopSim/AlternativeBranch/analysis-2fcf02fccca7ff2f21073fedbc66d65b73c873d5copy/two_population_analysis/Snakefile:
__init__() got an unexpected keyword argument 'metadata'
  File "/Users/vicentediegoortegadelvecchyo/Dropbox/Documents/LIIGH/Proyectos/PopSim/AlternativeBranch/analysis-2fcf02fccca7ff2f21073fedbc66d65b73c873d5copy/two_population_analysis/Snakefile", line 48, in <module>
  File "/Users/vicentediegoortegadelvecchyo/miniconda3/envs/popsim_env_test/lib/python3.6/site-packages/stdpopsim-0.1.dev149+gfe658a2-py3.6.egg/stdpopsim/drosophila_melanogaster.py", line 138, in __init__

Has anyone bumped into these errors before? Is there a quick way to fix them?

**Comment by andrewkern** [comment]
I'm fairly certain this is a version issue with the `stdpopsim` repo. Can you `git fetch upstream master` and `git pull upstream master` in that repo, reinstall, and then try again?

**Comment by dortegadelv** [comment]
Just tried doing that:

__popsim_env_test) vicente-diego-ortega-del-vecchyos-macbook-pro-3:stdpopsim vicentediegoortegadelvecchyo$ git fetch upstream master
warning: no common commits
remote: Enumerating objects: 285, done.
remote: Total 285 (delta 0), reused 0 (delta 0), pack-reused 285
Receiving objects: 100% (285/285), 1.28 MiB | 1.32 MiB/s, done.
Resolving deltas: 100% (135/135), done.
From https://github.com/popgensims/analysis
 * branch            master     -> FETCH_HEAD
 * [new branch]      master     -> upstream/master
(popsim_env_test) vicente-diego-ortega-del-vecchyos-macbook-pro-3:stdpopsim vicentediegoortegadelvecchyo$ git pull upstream master
From https://github.com/popgensims/analysis
 * branch            master     -> FETCH_HEAD
Auto-merging README.md
CONFLICT (add/add): Merge conflict in README.md
Auto-merging LICENSE
CONFLICT (add/add): Merge conflict in LICENSE
Automatic merge failed; fix conflicts and then commit the result.
(popsim_env_test) vicente-diego-ortega-del-vecchyos-macbook-pro-3:stdpopsim vicentediegoortegadelvecchyo$ python setup.py install
running install
..._


And I ran the snakemake file again and got the same error. Let me know if I am doing something wrong here or I am not following correctly your suggestion @andrewkern . Thanks.

**Comment by apragsdale** [comment]
Hey @dortegadelv - 
I've mostly caught up to speed with how your analysis pipeline is working (I had to change `msp` to `tsk` as the sample labels in `smc.py` because of the vcf output from the updated `msprime`), and I'm now getting the same error as @ckyriazis with `smc++`. It seems to be an issue with the `--base` flag, which lets you set the output file name something other than the default. I think that was a more recent change to the `smc++` code, so this could be a `smc++` version issue? What version do you have installed? (conda says mine is updated, with version `SMC++ v1.13.1`, but if you installed it differently, maybe you have a more recent version?)

Removing the `--base` flag and changing the relevant output copying lines in the Snakefile looks to have gotten around that issue for me.

**Comment by dortegadelv** [comment]
Hey @apragsdale , thanks for helping me debug this. My current version of smc++ is v1.15.2 , that might be the problem. I am going to check if I can run smc++ without the --base flag in the newest version of smc++.

**Comment by dortegadelv** [comment]
I think I fixed the problems with smc++ based on @apragsdale 's input in this new commit. Now smc.py does not use the --base flag. I did not have to change the msp to tsk as the sample labels in smc.py since the vcf files I was getting had msp as the sample labels. The updated Snakefile and smc.py files are ready to be tested @ckyriazis . Hope everything runs smoothly this time.

**Comment by ckyriazis** [comment]
Running it now @dortegadelv - seems to be working but I also had to change `msp` to `tsk`. If I dont run into any other issues, I'll merge this in with my updated pipeline with masking and then run that on the human and drosophila data.

**Comment by ckyriazis** [comment]
Hey @dortegadelv, I've been working on folding in your pipeline with smc++ with some updates I made to implement masking for dadi and fsc and everything seems to be working. 

The main thing left to do is implement masking for smc++. Would you be able to do that? @andrewkern has already done that for the the [n_t pipeline](https://github.com/popgensims/analysis/blob/master/n_t/smc.py) here so it should be relatively simple to translate what he did to the two population case.

**Comment by dortegadelv** [comment]
Hey @ckyriazis , I am on it. I just modified the pipeline to mask regions in smc++ following @andrewkern 's pipeline. I am running a test example. If things work well, I will update the pipeline in one day or two.

**Comment by andrewkern** [comment]
let me know if i can help at all along the way guys!

**Comment by dortegadelv** [comment]
I have implemented masking for smc++ following @andrewkern 's code. I think it is ready for you to take a look, @ckyriazis . You might need to change the labels msp to tsk.

@andrewkern : I copied your code in the function 'write_smcpp_file' from the smc.py file to update the function 'write_smcpp_file_twopops'. If you have a chance to take a look at my function to make sure I did not make a mistake, that would be very appreciated.

**Comment by andrewkern** [comment]
I will look at this in a bit, but just a heads up @dortegadelv and @ckyriazis-- @jeromekelleher has done a major refactor of `stdpopsim` that we are currently reviewing so we will need to do a bit of a rewrite on the simulation side of the two population pipeline once that is merged.

**Comment by ckyriazis** [comment]
Sounds good @andrewkern. I have an updated pipeline incorporating @dortegadelv's progress with smc++ and the masking I added for fsc and dadi that I am nearly ready to push. 

Also, just a note that I realized the problems I was having on my laptop (but not our lab computer) doing the masking was a pandas version issue - it worked with 0.24.2 but not 0.25.0. So perhaps we should specify that in requirements.txt

**Comment by jeromekelleher** [comment]
The changes upstream in [stdpopsim](https://github.com/popgensims/stdpopsim/pull/110) mean that this branch won't work now @dortegadelv and @ckyriazis. I've opened a PR with changes in #48 show the updates needed to work with the new stdpopsim API. Ideally, you should work with the CLI (as in the two population analysis), but the Python API is also reasonably convenient.

If you like, I can create a PR against this branch with the required changes to make your simulations work again. However, it would be good to do this after #48 is merged and you have [rebased](https://stdpopsim.readthedocs.io/en/latest/development.html#rebasing) your branch.

**Comment by ckyriazis** [comment]
Sounds good @jeromekelleher. I have a PR I'm nearly ready to send through with some updates on the analysis pipeline, so I can add the needed changes to that.

**Comment by andrewkern** [comment]
@ckyriazis is this PR ready for us?

**Comment by ckyriazis** [comment]
Hey @andrewkern - I made a new PR with a bunch of more recent updates called "updates for compatibility with stdpopsim changes" that needs review. Would be great if you could have a look at it (and perhaps try to run it) to see if everything looks ok.

**Comment by andrewkern** [comment]
closing this down as resolved with https://github.com/popgensims/analysis/pull/49

**Pull request closed without merging**
